import { MATERIALS, PAPER } from "../typings/types"

export const paperList: PAPER[] = [
  {
    "category": ["story", "vis+ai"],
    "tags": ['Human-AI Interaction', 'Storytelling', 'Vis Authoring', 'Animation', 'Visual Metaphors', 'AI4VIS'],
    "thumb": "./pub/datasway.gif",
    "title": "DataSway: Vivifying Metaphoric Visualization with Animation Clip Generation and Coordination",
    "authorsA": "Liwenhan Xie, Jiayi Zhou, Anyi Rao, Huamin Qu, ",
    "authorsB": "",
    "type": "Other",
    "year": 2025,
    "abbr": "arXiv",
    "full": "arXiv, 2025",
    "honor": "",
    "materials": {
      "Paper": "https://www.arxiv.org/pdf/2507.22051",
      "Homepage": "https://shellywhen.github.io/projects/DataSway",
      "Video": 'https://www.youtube.com/watch?v=4aMo1C6sY8s',
      "Demo": "https://shellywhen.github.io/datasway/",
      "Corpus": "https://datasway.notion.site/",
    } as MATERIALS
  },
  {
    "category": ["story", "vis+ai", "selected"],
    "tags": ['Human-AI Interaction', 'Vis Authoring', 'Storytelling', 'AI4VIS'],
    "thumb": "./pub/datawink.png",
    "title": "DataWink: Reusing and Adapting SVG-based Visualization Examples with Large Multimodal Models",
    "authorsA": "Liwenhan Xie, Yanna Lin, Can Liu, Huamin Qu, ",
    "authorsB": "",
    "type": "Journal",
    "year": 2025,
    "abbr": "VIS'25",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2025",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/abs/2507.17734",
      "Homepage": "https://shellywhen.github.io/projects/DataWink",
      "Video": 'https://www.youtube.com/watch?v=hSWl-XKrv88',
    } as MATERIALS
  },
  {
    "category": ["transform", "vis+ai", "selected"],
    "tags": ['Data Transformation', 'Human-AI Interaction', 'Trustworthy AI'],
    "thumb": "./pub/viseGPT.png",
    "title": "ViseGPT: Towards Better Alignment of LLM-generated Data Wrangling Scripts and User Prompts",
    "authorsA": "Jiajun Zhu*, Xinyu Cheng*, Zhongsu Luo, Yunfan Zhou, ",
    "authorsB": ", Di Weng, Yingcai Wu",
    "type": "Conference",
    "year": 2025,
    "abbr": "UIST'25",
    "full": "Proceedings of ACM Symposium on User Interface Software and Technology, 2025",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2508.01279",
    } as MATERIALS
  },
  {
    "category": ["story", "selected"],
    "tags": ['Animation', 'Visual Metaphors', 'Visual Analytics'],
    "thumb": "./pub/routeflow.png",
    "title": "RouteFlow: Trajectory-Aware Animated Transitions",
    "authorsA": "Duan Li, Xinyuan Guo, ",
    "authorsB": ", Lanxi Xiao, Lingyun Yu, Shixia Liu",
    "type": "Conference",
    "year": 2025,
    "abbr": "CHI'25",
    "full": "Proceedings of ACM Conference on Human Factors in Computing Systems, 2025",
    "honor": "Best Paper (50 of 5,014 submissions, top 1%)",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2502.08076",
      "Homepage": "https://trajectory-anim.github.io/",
      "Code": "https://github.com/Trajectory-Anim/Trajectory-Aware-Animated-Transitions",
      "DOI": "https://doi.org/10.1145/3706598.3714300",
    } as MATERIALS
  },
  {
    "category": ["vis+ai", "selected"],
    "tags": ['Human-AI Interaction', 'Education', 'Emotion'],
    "thumb": "./pub/fretmate.png",
    "title": "FretMate: ChatGPT-Powered Adaptive Guitar Learning Assistant",
    "authorsA": "Xin Shu, Lei Shi, Jiacheng Cheng, Lingling Ouyang, Mengdi Chu, ",
    "authorsB": "",
    "type": "Conference",
    "year": 2025,
    "abbr": "IUI'25",
    "full": "Proceedings of International Conference on Intelligent User Interfaces, 2025",
    "honor": "",
    "materials": {
      "Paper":"./pub/FretMate.pdf",
      "DOI": "https://dl.acm.org/doi/full/10.1145/3708359.3712080",
    } as MATERIALS
  },
  {
    "category": ["literacy", "story", "selected"],
    "tags": ['Visual Analytics', 'AI/Data Literacy', 'Education'],
    "thumb": "./pub/patternexplainer.png",
    "title": "Does This Have a Particular Meaning? Interactive Pattern Explanation for Network Visualizations",
    "authorsA": "",
    "authorsB": ", Alexis Pister, Junxiu Tang, Fanny Chevalier, Benjamin Bach",
    "type": "Journal",
    "year": 2024,
    "abbr": "VIS'24",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2024",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2408.01272",
      "Video": './pub/patternexplainer.mp4',
      "DOI": "https://doi.org/10.1109/TVCG.2024.3456192",
    } as MATERIALS
  },
  {
    "category": ["story", 'literacy'],
    "tags": ['Storytelling', 'Digital Humanities'],
    "thumb": "./pub/visatlas.png",
    "title": "Visualization Atlases: Explaining and Exploring Complex Topics through Data, Visualization, and Narration",
    "authorsA": "Jinrui Wang, ",
    "authorsB": ", Benjamin Bach, Uta Hinrichs",
    "type": "Journal",
    "year": 2024,
    "abbr": "VIS'24",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2024",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2408.07483",
      "Homepage": "https://vis-atlas.github.io/",
      "DOI": "https://doi.org/10.1109/TVCG.2024.3456311",
    } as MATERIALS
  },
  {
    "category": ["transform", 'vis+ai'],
    "tags": ['Data Transformation', 'Human-AI Interaction', 'Trustworthy AI'],
    "thumb": "./pub/ferry.png",
    "title": "Ferry: Toward Better Understanding of Input/Output Space for Data Wrangling Scripts",
    "authorsA": "Zhongsu Luo, Kai Xiong, Jiajun Zhu, Ran Chen, ",
    "authorsB": ", Di Weng, Yingcai Wu",
    "type": "Journal",
    "year": 2024,
    "abbr": "VIS'24",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2024",
    "honor": "",
    "materials": {
      "Paper": "./pub/ferry.pdf",
      "DOI": "https://doi.org/10.1109/TVCG.2024.3456328",
    } as MATERIALS
  },
  {
    "category": ["art"],
    "tags": ['Data Art', 'Digital Humanities', 'Creativity'],
    "thumb": "./pub/PoP.jpg",
    "title": "Pieces of Peace: Women and Gender in Peace Agreements",
    "authorsA": "Jenny Long, Jinrui Wang, Tomas Vancisin, Laura Wise, ",
    "authorsB": ", Tara Capel, Uta Hinrichs",
    "type": "Other",
    "year": 2024,
    "abbr": "VISAP'24",
    "full": "IEEE VIS Arts Program (in both Pictorial and Artwork tracks), 2024",
    "honor": "",
    "materials": {
      "Paper": "./pub/PoP.pdf",
      "Video": "./pub/pop.mp4",
      "DOI": "https://doi.org/10.1109/VISAP64569.2024.00007",
    } as MATERIALS
  },
  {
    "category": ["art"],
    "tags": ['Data Art', 'Digital Humanities', 'Creativity'],
    "thumb": "./pub/loss.jpg",
    "title": "Loss of Sonnet 18",
    "authorsA": "Junxiu Tang, Jiayi Zhou, Yifang Wang, ",
    "authorsB": ", Peiquan Xia, Xiaojiao Chen, Tan Tang, Yingcai Wu",
    "type": "Other",
    "year": 2024,
    "abbr": "SIGGRAPH'24",
    "full": "ACM SIGGRAPH Art Gallery, 2024",
    "honor": "",
    "materials": {
      "Paper": "https://osf.io/6jm9x",
      "Video": "https://osf.io/6xhfj",
      "Appendix": "https://osf.io/kjtrb/",
      "DOI": "https://dl.acm.org/doi/abs/10.1145/3641523.3669939",
    } as MATERIALS
  },
  {
    "category": ["story"],
    "tags": ['Storytelling', 'Animation', 'Vis Authoring'],
    "thumb": "./pub/wonderflow.png",
    "title": "WonderFlow: Narration-Centric Design of Animated Data Videos",
    "authorsA": "Yun Wang*, Leixian Shen*, Zhengxin You, ",
    "authorsB": ", Bongshin Lee, John Thompson, Haidong Zhang, Dongmei Zhang",
    "type": "Journal",
    "year": 2024,
    "abbr": "TVCG'24",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2024",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2308.04040",
      "Homepage": "https://datavideos.github.io/WonderFlow/#/homepage",
      "DOI": "https://doi.org/10.1109/TVCG.2024.3411575",
    } as MATERIALS
  },
  {
    "category": ["transform"],
    "tags": ['Data Transformation', 'Visual Metaphors', 'Storytelling'],
    "thumb": "./pub/table-illustrator.png",
    "title": "Table Illustrator: Puzzle-based Interactive Authoring of Plain Tables",
    "authorsA": "Yanwei Huang, Yurun Yang, ",
    "authorsB": ", Ran Chen, Di Weng, Yingcai Wu",
    "type": "Conference",
    "year": 2024,
    "abbr": "CHI'24",
    "full": "Proceedings of ACM Conference on Human Factors in Computing Systems, 2024",
    "honor": "",
    "materials": {
      "Paper": "./pub/chi24_Table_Illustrator.pdf",
      "Video": "https://www.youtube.com/watch?v=OrFKL5-Fc1Y",
      "Demo": "https://yhuang.top/tableshop/",
      "Code": "https://github.com/Ais0n/tableshop",
      "DOI": "https://doi.org/10.1145/3613904.3642415",
    } as MATERIALS
  },
  {
    "category": ["vis+ai", "transform"],
    "tags": ['Data Transformation', 'Human-AI Interaction', 'Trustworthy AI'],
    "thumb": "./pub/NL2Rigel.png",
    "title": "Interactive Table Synthesis with Natural Language",
    "authorsA": "Yanwei Huang, Yunfan Zhou, Ran Chen, Changhao Pan, ",
    "authorsB": ", Di Weng, Yingcai Wu",
    "type": "Journal",
    "year": 2023,
    "abbr": "TVCG'23",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2023",
    "honor": "",
    "materials": {
      "Paper": "./pub/nl2rigel.pdf",
      "Video": "https://www.youtube.com/watch?v=qjjKAykyDZU",
      "DOI": "https://doi.org/10.1109/TVCG.2023.3329120",
    } as MATERIALS
  },
  {
    "category": ["art"],
    "tags": ['Data Art', 'Digital Humanities', 'Creativity'],
    "thumb": "./pub/island.jpeg",
    "title": "Posts with no Response: The Island of Loneliness",
    "authorsA": "Junxiu Tang, Rui Sheng, Yifang Wang, ",
    "authorsB": ", Xiaojiao Chen, Tan Tang, Yingcai Wu",
    "type": "Other",
    "year": 2023,
    "abbr": "VISAP'23",
    "full": "IEEE VIS Arts Program (in both Pictorial and Artwork tracks), 2023",
    "honor": "",
    "materials": {
      "Paper": "./pub/island.pdf",
      "Video": "./pub/island.mp4",
      "Appendix": "https://osf.io/3kt8d/",
      "Exhibition": "https://visap.net/2023/contributions/posts-with-no-response-the-island-of-loneliness/",
      "Blog": "https://library.hkust.edu.hk/sc/the-island-of-loneliness-china-visap/",
      "DOI": "https://doi.org/10.1109/VISAP60414.2023.00007"
    } as MATERIALS
  },
  {
    "category": ["story"],
    "tags": ['Storytelling', 'Emotion', 'Animation', 'Vis Authoring'],
    "thumb": "./pub/emordle.gif",
    "title": "Creating Emordle: Animating Word Cloud for Emotion Expression",
    "authorsA": "Liwenhan Xie, ",
    "authorsB": ", Jeon Cheol Su, Yun Wang, Siming Chen, Huamin Qu",
    "type": "Journal",
    "year": 2023,
    "abbr": "TVCG'23",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2023",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2306.07560.pdf",
      "Homepage": "https://shellywhen.github.io/projects/emordle",
      "Demo": "https://shellywhen.github.io/EmotionalWordle/#/",
      "Corpus": "https://drive.google.com/drive/folders/1RUOj6fBNlq6nFDGeHAbZn7zayHtnJkuY",
      "DOI": "https://doi.org/10.1109/TVCG.2023.3286392",
    } as MATERIALS
  },
  {
    "category": ["vis+ai", "story", 'selected'],
    "tags": ['Human-AI Interaction', 'Visual Metaphors', 'Vis Authoring', 'Storytelling', 'AI4VIS'],
    "thumb": "./pub/metaglyph.png",
    "title": "MetaGlyph: Automatic Generation of Metaphoric Glyph-based Visualization",
    "authorsA": "Lu Ying, ",
    "authorsB": ", Dazhen Deng, Yuchen Yang, Tan Tang, Lingyun Yu, Yingcai Wu",
    "type": "Journal",
    "year": 2022,
    "abbr": "VIS'22",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2022",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2209.05739",
      "DOI": "https://doi.org/10.1109/TVCG.2022.3209447",
    } as MATERIALS
  },
  {
    "category": ["transform"],
    "tags": ['Data Transformation'],
    "thumb": "./pub/rigel.png",
    "title": "Rigel: Transforming Tabular Data by Declarative Mapping",
    "authorsA": "Ran Chen, Di Weng, Yanwei Huang, ",
    "authorsB": ", Jiayi Zhou, Guodao Sun, Yingcai Wu",
    "type": "Journal",
    "year": 2022,
    "abbr": "VIS'22",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2022",
    "honor": "",
    "materials": {
      "Paper": "./pub/rigel.pdf",
      "Demo": "https://rigel-system.github.io/rigel-system/",
      "Github": "https://github.com/rigel-js",
      "Video": "https://www.youtube.com/watch?v=fvM_W-1n7N4",
      "Appendix": "https://observablehq.com/@rigel/appendix",
      "DOI":"https://doi.org/10.1109/TVCG.2022.3209385"
    } as MATERIALS
  },
  {
    "category": ["vis+ai"],
    "tags": ['VIS4AI', 'Visual Analytics'],
    "thumb": "./pub/visimages.png",
    "title": "VisImages: A Fine-Grained Expert-Annotated Visualization Dataset",
    "authorsA": "Dazhen Deng, Yihong Wu, ",
    "authorsB": ", Jiang Wu, Siwei Fu, Weiwei Cui, Yingcai Wu",
    "type": "Journal",
    "year": 2022,
    "abbr": "TVCG",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2022",
    "honor": "",
    "materials": {
      "Paper": "./pub/visimages.pdf",
      "Homepage": "https://visimages.github.io/",
      "DOI": "https://doi.org/10.1109/TVCG.2022.3155440"
    } as MATERIALS
  },
  {
    "category": ["va"],
    "tags": ['Visual Analytics', 'Sports'],
    "thumb": "./pub/rallycomparotor.png",
    "title": "RallyComparator: visual comparison of the multivariate and spatial stroke sequence in table tennis rally",
    "authorsA": "Ji Lan, Jiachen Wang, ",
    "authorsB": ", Zheng Zhou, Hui Zhang, Yingcai Wu",
    "type": "Journal",
    "year": 2021,
    "abbr": "ChinaVis'21",
    "full": "Journal of Visualization, 2021",
    "honor": "",
    "materials": {
      "Paper": "./pub/rallycomparator.pdf",
      "DOI": "https://doi.org/10.1007/s12650-021-00772-0"
    } as MATERIALS
  },
  {
    "category": ["vis+ai", 'selected'],
    "thumb": "./pub/ai4vis.png",
    "tags": ['AI4VIS'],
    "title": "AI4VIS: Survey on Artificial Intelligence Approaches for Data Visualization",
    "authorsA": "Aoyu Wu, Yun Wang, ",
    "authorsB": ", Dominik Moritz, Weiwei Cui, Haidong Zhang, Dongmei Zhang, Huamin Qu",
    "type": "Journal",
    "abbr": "TVCG'21",
    "year": 2021,
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2021",
    "honor": "",
    "materials": {
      "Paper": "./pub/ai4vis.pdf",
      "Homepage": "http://ai4vis.github.io",
      "DOI": "https://doi.org/10.1109/TVCG.2021.3099002"
    } as MATERIALS
  },
  {
    "category": ["va"],
    "tags": ['Visual Analytics', 'Sports'],
    "thumb": "./pub/tacValuer.png",
    "title": "Tac-Valuer: Knowledge-based Stroke Evaluation in Table Tennis",
    "authorsA": "Jiachen Wang, Dazhen Deng, Xiao Xie, ",
    "authorsB": ", Yu-Xuan Huang, Le-Wen Cai, Hui Zhang, Min-Ling Zhang, Zhi-Hua Zhou, Yingcai Wu",
    "type": "Conference",
    "year": 2021,
    "abbr": "KDD'21",
    "full": "Proceedings of Conference on Knowledge Discovery and Data Mining, 2021",
    "honor": "",
    "materials": {
      "Paper": "./pub/tacValuer.pdf",
      "DOI": "https://doi.org/10.1145/3447548.3467104"
    } as MATERIALS
  },
  {
    "category": ["transform"],
    "tags": ['Data Transformation', 'Vis Authoring'],
    "thumb": "./pub/nebula.png",
    "title": "Nebula: A Coordinating Grammar of Graphics",
    "authorsA": "Ran Chen, ",
    "authorsB": ", Jiahui Chen, Di Weng, Junxiu Tang, Siwei Fu, Yingcai Wu",
    "type": "Journal",
    "abbr": "TVCG'21",
    "year": 2021,
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2021",
    "honor": "",
    "materials": {
      "Paper": "./pub/nebula.pdf",
      "Homepage": "https://nebula-vis.github.io/examples",
      "DOI": "https://doi.org/10.1109/TVCG.2021.3076222"
    } as MATERIALS
  }, 
  {
    "category": ["others"],
    "tags": ['Digital Humanities', 'Visual Analytics'],
    "thumb": "./pub/careerflow.png",
    "title": "Interactive Visual Exploration of Longitudinal Historical Career Mobility Data",
    "authorsA": "Yifang Wang, Hongye Liang, ",
    "authorsB": ", Jiachen Wang, Ke Xu, Zikun Deng, Cameron Campbell, Bijia Chen, Yingcai Wu, Huamin Qu",
    "type": "Journal",
    "year": 2021,
    "abbr": "TVCG'21",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2021",
    "honor": "",
    "materials": {
      "Paper": "./pub/careerflow.pdf",
      "Video": "./pub/careerflow.mp4",
      "DOI": "https://doi.org/10.1109/TVCG.2021.3067200"
    } as MATERIALS
  },
  {
    "category": ["story", 'selected'],
    "tags": ['Storytelling', 'Animation'],
    "thumb": "./pub/datagif.gif",
    "title": "What Makes a Data-GIF Understandable?",
    "authorsA": "",
    "authorsB": ", Aoyu Wu, Junxiu Tang, Benjamin Bach, Yingcai Wu, Huamin Qu",
    "type": "Journal",
    "year": 2020,
    "abbr": "VIS'20",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2020",
    "honor": "",
    "materials": {
      "Paper": "http://arxiv.org/pdf/2008.07227",
      "Video": "https://youtu.be/PFLrrK_4jj0",
      "Homepage": "https://data-gifs.github.io/",
      "DOI": "https://doi.org/10.1109/TVCG.2020.3030396"
    } as MATERIALS
  },
  {
    "category": ["story"],
    "tags": ['Storytelling', 'Animation'],
    "thumb": "./pub/transition.png",
    "title": "Narrative Transitions in Data Videos",
    "authorsA": "Junxiu Tang, Lingyun Yu, Tan Tang, ",
    "authorsB": ", Lu Ying, Yuhua Zhou, Peiran Ren, Yingcai Wu",
    "type": "Other",
    "year": 2020,
    "abbr": "VIS'20",
    "full": "IEEE VIS Conference Short Paper, 2020",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/2009.05233",
      "Homepage": "https://narrativetransitions.github.io/home/",
      "Video": "https://www.youtube.com/watch?v=RNFCuR9DgMg",
      "DOI": "https://doi.org/10.1109/VIS47514.2020.00037"
    } as MATERIALS
  },
  {
    "category": ["story", 'selected'],
    "tags": ['Storytelling', 'Animation', 'Vis Authoring'],
    "thumb": "./pub/dancingwords.png",
    "title": "DancingWords: Exploring Animated Word Clouds to Tell Stories",
    "authorsA": "",
    "authorsB": ", Jiang Wu, Xinke Wu, Hongye Liang, Weiwei Cui, Yingcai Wu, Huamin Qu",
    "type": "Journal",
    "year": 2020,
    "abbr": "ChinaVis'20",
    "full": "Journal of Visualization, 2020",
    "honor": "Best Paper Honorable Mention",
    "materials": {
      "Paper": "./pub/dancingwords.pdf",
      "Video": "./pub/dancingwords.mp4",
      "Homepage": "http://dancingwords.github.io/",
      "DOI": "https://doi.org/10.1007/s12650-020-00689-0"
    } as MATERIALS
  },
  {
    "category": ["va"],
    "tags": ['Visual Analytics', 'Emotion', 'Education'],
    "thumb": "./pub/EmotionCues.png",
    "title": "EmotionCues: Emotion-Oriented Visual Summarization of Classroom Videos",
    "authorsA": "Haipeng Zeng, ",
    "authorsB": ", Yanbang Wang, Yong Wang, Liguo Zhang, Ting-Chuen Pong, Huamin Qu",
    "type": "Journal",
    "year": 2020,
    "abbr": "TVCG'20",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2020",
    "honor": "",
    "materials": {
      "Paper": "./pub/EmotionCues.pdf",
      "DOI": "https://doi.org/10.1109/TVCG.2019.2963659",
    } as MATERIALS
  },
  {
    "category": ["story"],
    "tags": ['Storytelling'],
    "thumb": "./pub/pulse.jpg",
    "title": "Pulse: Toward a Smart Campus by Communicating Real-time Wi-Fi Access Data",
    "authorsA": "Aoyu Wu, Bon Kyung Ku, Furui Cheng, ",
    "authorsB": ", Abishek Puri, Yifang Wang, Huamin Qu",
    "type": "Other",
    "year": 2018,
    "abbr": "VIS'18",
    "full": "Workshop on Visualization for Communication, 2018",
    "honor": "",
    "materials": {
      "Paper": "https://arxiv.org/pdf/1810.00161.pdf",
    } as MATERIALS
  },
  {
    "category": ["others"],
    "tags": ['Visual Analytics'],
    "thumb": "./pub/BitExTract.png",
    "title": "BitExTract: Interactive Visualization for Extracting Bitcoin Exchange Intelligence",
    "authorsA": "Xuanwu Yue, ",
    "authorsB": ", Xinyu Zhu, Xinnan Du, Zheqing Yu, Dimitrios Papadopoulos, Siyuan Liu",
    "type": "Journal",
    "year": 2018,
    "abbr": "VIS'18",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2018",
    "honor": "",
    "materials": {
      "Paper": "./pub/BitExTract.pdf",
      "Video": "https://www.youtube.com/watch?v=gVgO03qRAlI",
      "DOI": "https://doi.org/10.1109/TVCG.2018.2864814"
    } as MATERIALS
  },
  {
    "category": ["va"],
    "tags": ['Visual Analytics', 'Sports'],
    "thumb": "./pub/iTTVis.png",
    "title": "iTTVis: Interactive Visualization of Table Tennis Data",
    "authorsA": "Yingcai Wu, Ji Lan, ",
    "authorsB": ", Chenyang Ji, Kejian Zhao, Jiachen Wang, Hui Zhang",
    "type": "Journal",
    "year": 2017,
    "abbr": "VIS'17",
    "full": "IEEE Transactions on Visualization and Computer Graphics, 2017",
    "honor": "",
    "materials": {
      "Paper": "./pub/iTTVis.pdf",
      "Video": "./pub/iTTVis.mp4",
      "DOI": "https://doi.org/10.1109/TVCG.2017.2744218"
    } as MATERIALS
  },
]